# Generated by Django 6.0 on 2026-01-13 18:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Driver's full name", max_length=100)),
                ('phone_number', models.CharField(help_text="Driver's phone number", max_length=20)),
                ('email', models.EmailField(help_text="Driver's email address for trip assignments", max_length=254)),
                ('car_number', models.CharField(help_text='License plate or car identification number', max_length=50, verbose_name='Plate Number')),
                ('car_type', models.CharField(help_text='Vehicle type (e.g., Sedan, SUV, Van)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether driver is currently available')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this driver')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_confirmed_edits', models.BooleanField(default=False, help_text='Allow users to edit bookings after confirmation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(blank=True, help_text='Unique booking reference number', max_length=20, null=True, unique=True)),
                ('passenger_name', models.CharField(help_text='Full name of passenger', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passenger_email', models.EmailField(blank=True, help_text='Passenger email for communication', max_length=254, null=True)),
                ('pick_up_address', models.CharField(max_length=255)),
                ('drop_off_address', models.CharField(blank=True, max_length=255, null=True)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('return_pickup_address', models.CharField(blank=True, max_length=255, null=True)),
                ('return_dropoff_address', models.CharField(blank=True, max_length=255, null=True)),
                ('return_flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('return_special_requests', models.TextField(blank=True, null=True)),
                ('return_admin_response', models.TextField(blank=True, null=True)),
                ('return_processed', models.BooleanField(default=False)),
                ('is_return_trip', models.BooleanField(default=False, help_text='True if this booking is the return leg of a round trip')),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Sprinter Van', 'Sprinter Van'), ('Others', 'Others')], max_length=20)),
                ('trip_type', models.CharField(choices=[('Point', 'Point-to-Point'), ('Round', 'Round Trip'), ('Hourly', 'Hourly')], max_length=10)),
                ('hours_booked', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_passengers', models.PositiveIntegerField(default=1)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Cancelled_Full_Charge', 'Cancelled (Full Charge)'), ('Customer_No_Show', 'Customer No-Show'), ('Trip_Not_Covered', 'Trip Not Covered'), ('Trip_Completed', 'Trip Completed')], db_index=True, default='Pending', max_length=25)),
                ('admin_reviewed', models.BooleanField(default=False, help_text='True if admin has reviewed/confirmed this booking')),
                ('admin_comment', models.TextField(blank=True, help_text='Internal admin notes (not visible to customer)', null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('customer_communication', models.TextField(blank=True, help_text='Admin response to customer special requests (visible to customer)', null=True)),
                ('communication_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when customer communication was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_notified_at', models.DateTimeField(blank=True, help_text='When the driver was notified about this assignment', null=True)),
                ('driver_response_status', models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Trip Completed')], default='pending', help_text="Driver's response to the trip assignment", max_length=20)),
                ('driver_rejection_reason', models.TextField(blank=True, help_text='Reason provided by driver for rejecting the trip', null=True)),
                ('driver_response_at', models.DateTimeField(blank=True, help_text='When the driver responded to the assignment', null=True)),
                ('driver_completed_at', models.DateTimeField(blank=True, help_text='When the driver marked the trip as completed', null=True)),
                ('driver_payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed payment amount for the driver', max_digits=10, null=True)),
                ('driver_paid', models.BooleanField(default=False, help_text='Whether the driver has been paid for this trip')),
                ('driver_paid_at', models.DateTimeField(blank=True, help_text='When the driver was marked as paid', null=True)),
                ('driver_admin_note', models.TextField(blank=True, help_text='Admin note visible to driver about this trip (e.g., check portal for updates)', null=True)),
                ('share_driver_info', models.BooleanField(default=False, help_text='Share driver name, vehicle, and phone with customer')),
                ('driver_paid_by', models.ForeignKey(blank=True, help_text='Admin who marked the driver as paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_payments_processed', to=settings.AUTH_USER_MODEL)),
                ('linked_booking', models.ForeignKey(blank=True, help_text='For round trips, links outbound and return bookings together', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_trips', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('assigned_driver', models.ForeignKey(blank=True, help_text='Driver assigned to this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='bookings.driver')),
            ],
            options={
                'ordering': ['-pick_up_date', '-pick_up_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('cancelled', 'Cancelled'), ('driver_assigned', 'Driver Assigned'), ('driver_rejected', 'Driver Rejected'), ('driver_completed', 'Driver Completed Trip')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('booking_snapshot', models.JSONField(help_text='Complete booking data at this point in time')),
                ('changes', models.JSONField(blank=True, help_text="Dictionary of field changes: {'field_name': {'old': value, 'new': value}}", null=True)),
                ('change_reason', models.TextField(blank=True, help_text='Reason for the change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of user making change', null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking History',
                'verbose_name_plural': 'Booking Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_confirmed', models.BooleanField(default=False, help_text='Allow this user to edit confirmed bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Permission',
                'verbose_name_plural': 'Booking Permissions',
            },
        ),
        migrations.CreateModel(
            name='BookingStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('stop_number', models.PositiveIntegerField()),
                ('is_return_stop', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Stop',
                'verbose_name_plural': 'Booking Stops',
                'ordering': ['is_return_stop', 'stop_number'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('sms', 'SMS'), ('in_person', 'In Person'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(help_text='Details of the communication')),
                ('communication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='bookings.booking')),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'ordering': ['-communication_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('booking_new', 'New Booking'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_status_change', 'Status Change'), ('booking_reminder', 'Pickup Reminder'), ('driver_assignment', 'Driver Assignment'), ('round_trip_new', 'Round Trip - New'), ('round_trip_confirmed', 'Round Trip - Confirmed'), ('round_trip_cancelled', 'Round Trip - Cancelled'), ('round_trip_status_change', 'Round Trip - Status Change')], help_text='Type of notification this template is used for', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Friendly name for this template', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Internal notes about this template's purpose")),
                ('subject_template', models.CharField(help_text='Subject line. Use {variable_name} for dynamic content. Example: Trip Confirmed: {passenger_name} - {pick_up_date}', max_length=200)),
                ('html_template', models.TextField(help_text='HTML email body. Use {variable_name} for dynamic content. Available variables documented below.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates will fall back to file-based templates')),
                ('send_to_user', models.BooleanField(default=True, help_text="Send to booking user's email")),
                ('send_to_admin', models.BooleanField(default=True, help_text='Send to admin emails')),
                ('send_to_passenger', models.BooleanField(default=False, help_text='Send to passenger email (if different from user)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sent', models.IntegerField(default=0, help_text='Total number of emails sent using this template')),
                ('total_failed', models.IntegerField(default=0, help_text='Total number of failed sends')),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='Last time this template was used', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='FrequentPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('preferred_vehicle_type', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Sprinter Van', 'Sprinter Van'), ('Others', 'Others')], help_text='Preferred vehicle type for this passenger', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequent_passengers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new', 'New Booking'), ('confirmed', 'Booking Confirmed'), ('cancelled', 'Booking Cancelled'), ('status_change', 'Status Changed'), ('reminder', 'Pickup Reminder'), ('driver_assignment', 'Driver Assignment')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_log', to='bookings.booking')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_new', models.BooleanField(default=True)),
                ('notify_confirmed', models.BooleanField(default=True)),
                ('notify_cancelled', models.BooleanField(default=True)),
                ('notify_status_changes', models.BooleanField(default=True, help_text='Receive emails for booking status changes')),
                ('notify_reminders', models.BooleanField(default=True, help_text='Receive pickup reminder emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Recipient',
                'verbose_name_plural': 'Notification Recipients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_notifications', to='bookings.notificationrecipient')),
            ],
            options={
                'verbose_name': 'Booking Notification',
                'verbose_name_plural': 'Booking Notifications',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text="User's contact phone number", max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, help_text="User's company name (optional)", max_length=200, null=True)),
                ('receive_booking_confirmations', models.BooleanField(default=True, help_text='Receive emails when bookings are confirmed')),
                ('receive_status_updates', models.BooleanField(default=True, help_text='Receive emails when booking status changes')),
                ('receive_pickup_reminders', models.BooleanField(default=True, help_text='Receive reminder emails before pickup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ViewedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, help_text='When this activity was viewed')),
                ('activity', models.ForeignKey(help_text='The activity that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='bookings.bookinghistory')),
                ('user', models.ForeignKey(help_text='Admin user who viewed this activity', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viewed Activity',
                'verbose_name_plural': 'Viewed Activities',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, help_text='When this booking was viewed')),
                ('booking', models.ForeignKey(help_text='The booking that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by_users', to='bookings.booking')),
                ('user', models.ForeignKey(help_text='User who viewed this booking', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viewed Booking',
                'verbose_name_plural': 'Viewed Bookings',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notes', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Admin Note',
                'verbose_name_plural': 'Admin Notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', '-created_at'], name='bookings_ad_booking_c44447_idx'), models.Index(fields=['staff_member'], name='bookings_ad_staff_m_e718d8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['booking', '-changed_at'], name='bookings_bo_booking_bb647d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['changed_by'], name='bookings_bo_changed_dfb33a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['action'], name='bookings_bo_action_e99e27_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpermission',
            index=models.Index(fields=['user'], name='bookings_bo_user_id_478ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstop',
            index=models.Index(fields=['booking'], name='bookings_bo_booking_f12b3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingstop',
            unique_together={('booking', 'stop_number', 'is_return_stop')},
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['booking', '-communication_date'], name='bookings_co_booking_98e59c_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['staff_member'], name='bookings_co_staff_m_93871b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'pick_up_date'], name='bookings_bo_status_4a5887_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'pick_up_date'], name='bookings_bo_user_id_1bbb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pick_up_date'], name='bookings_bo_pick_up_c5433d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_bo_booking_8a7545_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pick_up_date', 'status'], name='bookings_bo_pick_up_11a556_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['template_type', 'is_active'], name='bookings_em_templat_2780bb_idx'),
        ),
        migrations.AddIndex(
            model_name='frequentpassenger',
            index=models.Index(fields=['user'], name='bookings_fr_user_id_d636a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frequentpassenger',
            unique_together={('user', 'name', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['booking', 'notification_type'], name='bookings_no_booking_e08869_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent_at'], name='bookings_no_sent_at_04f4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['success'], name='bookings_no_success_1375b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['is_active'], name='bookings_no_is_acti_3b5314_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['email'], name='bookings_no_email_568f08_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingnotification',
            index=models.Index(fields=['booking'], name='bookings_bo_booking_a1b2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingnotification',
            index=models.Index(fields=['recipient'], name='bookings_bo_recipie_931d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingnotification',
            unique_together={('booking', 'recipient')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='bookings_us_user_id_47189a_idx'),
        ),
        migrations.AddIndex(
            model_name='viewedactivity',
            index=models.Index(fields=['user', 'activity'], name='bookings_vi_user_id_e60fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='viewedactivity',
            index=models.Index(fields=['viewed_at'], name='bookings_vi_viewed__686797_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='viewedactivity',
            unique_together={('user', 'activity')},
        ),
        migrations.AddIndex(
            model_name='viewedbooking',
            index=models.Index(fields=['user', 'booking'], name='bookings_vi_user_id_84bcf2_idx'),
        ),
        migrations.AddIndex(
            model_name='viewedbooking',
            index=models.Index(fields=['viewed_at'], name='bookings_vi_viewed__46bd17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='viewedbooking',
            unique_together={('user', 'booking')},
        ),
    ]
