# Generated by Django 6.0 on 2025-12-24 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_confirmed_edits', models.BooleanField(default=False, help_text='Allow users to edit bookings after confirmation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(blank=True, help_text='Unique booking reference number', max_length=20, null=True, unique=True)),
                ('passenger_name', models.CharField(help_text='Full name of passenger', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passenger_email', models.EmailField(blank=True, help_text='Passenger email for communication', max_length=254, null=True)),
                ('pick_up_address', models.CharField(max_length=255)),
                ('drop_off_address', models.CharField(blank=True, max_length=255, null=True)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('return_pickup_address', models.CharField(blank=True, max_length=255, null=True)),
                ('return_dropoff_address', models.CharField(blank=True, max_length=255, null=True)),
                ('return_flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('return_special_requests', models.TextField(blank=True, null=True)),
                ('return_admin_response', models.TextField(blank=True, null=True)),
                ('return_processed', models.BooleanField(default=False)),
                ('is_return_trip', models.BooleanField(default=False, help_text='True if this booking is the return leg of a round trip')),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Sprinter Van', 'Sprinter Van'), ('Others', 'Others')], max_length=20)),
                ('trip_type', models.CharField(choices=[('Point', 'Point-to-Point'), ('Round', 'Round Trip'), ('Hourly', 'Hourly')], max_length=10)),
                ('hours_booked', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_passengers', models.PositiveIntegerField(default=1)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Cancelled_Full_Charge', 'Cancelled (Full Charge)'), ('Customer_No_Show', 'Customer No-Show'), ('Trip_Not_Covered', 'Trip Not Covered'), ('Trip_Completed', 'Trip Completed')], db_index=True, default='Pending', max_length=25)),
                ('admin_comment', models.TextField(blank=True, help_text='Internal admin notes (not visible to customer)', null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('customer_communication', models.TextField(blank=True, help_text='Admin response to customer special requests (visible to customer)', null=True)),
                ('communication_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when customer communication was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_booking', models.ForeignKey(blank=True, help_text='For round trips, links outbound and return bookings together', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_trips', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pick_up_date', '-pick_up_time'],
            },
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notes', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Admin Note',
                'verbose_name_plural': 'Admin Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_confirmed', models.BooleanField(default=False, help_text='Allow this user to edit confirmed bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Permission',
                'verbose_name_plural': 'Booking Permissions',
            },
        ),
        migrations.CreateModel(
            name='BookingStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('stop_number', models.PositiveIntegerField()),
                ('is_return_stop', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Stop',
                'verbose_name_plural': 'Booking Stops',
                'ordering': ['is_return_stop', 'stop_number'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('sms', 'SMS'), ('in_person', 'In Person'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(help_text='Details of the communication')),
                ('communication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='bookings.booking')),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'ordering': ['-communication_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrequentPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequent_passengers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new', 'New Booking'), ('confirmed', 'Booking Confirmed'), ('cancelled', 'Booking Cancelled'), ('status_change', 'Status Changed'), ('reminder', 'Pickup Reminder')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_log', to='bookings.booking')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_new', models.BooleanField(default=True)),
                ('notify_confirmed', models.BooleanField(default=True)),
                ('notify_cancelled', models.BooleanField(default=True)),
                ('notify_status_changes', models.BooleanField(default=True, help_text='Receive emails for booking status changes')),
                ('notify_reminders', models.BooleanField(default=True, help_text='Receive pickup reminder emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Recipient',
                'verbose_name_plural': 'Notification Recipients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_notifications', to='bookings.notificationrecipient')),
            ],
            options={
                'verbose_name': 'Booking Notification',
                'verbose_name_plural': 'Booking Notifications',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text="User's contact phone number", max_length=20, null=True)),
                ('receive_booking_confirmations', models.BooleanField(default=True, help_text='Receive emails when bookings are confirmed')),
                ('receive_status_updates', models.BooleanField(default=True, help_text='Receive emails when booking status changes')),
                ('receive_pickup_reminders', models.BooleanField(default=True, help_text='Receive reminder emails before pickup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'pick_up_date'], name='bookings_bo_status_4a5887_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pick_up_date'], name='bookings_bo_pick_up_c5433d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_bo_booking_8a7545_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnote',
            index=models.Index(fields=['booking', '-created_at'], name='bookings_ad_booking_c44447_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnote',
            index=models.Index(fields=['staff_member'], name='bookings_ad_staff_m_e718d8_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpermission',
            index=models.Index(fields=['user'], name='bookings_bo_user_id_478ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstop',
            index=models.Index(fields=['booking'], name='bookings_bo_booking_f12b3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingstop',
            unique_together={('booking', 'stop_number', 'is_return_stop')},
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['booking', '-communication_date'], name='bookings_co_booking_98e59c_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['staff_member'], name='bookings_co_staff_m_93871b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='bookings_cu_user_id_dc4a91_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='bookings_cu_phone_n_d34941_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='bookings_cu_created_e6bb89_idx'),
        ),
        migrations.AddIndex(
            model_name='frequentpassenger',
            index=models.Index(fields=['user'], name='bookings_fr_user_id_d636a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frequentpassenger',
            unique_together={('user', 'name', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['booking', 'notification_type'], name='bookings_no_booking_e08869_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent_at'], name='bookings_no_sent_at_04f4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['success'], name='bookings_no_success_1375b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['is_active'], name='bookings_no_is_acti_3b5314_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['email'], name='bookings_no_email_568f08_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingnotification',
            index=models.Index(fields=['booking'], name='bookings_bo_booking_a1b2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingnotification',
            index=models.Index(fields=['recipient'], name='bookings_bo_recipie_931d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingnotification',
            unique_together={('booking', 'recipient')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='bookings_us_user_id_47189a_idx'),
        ),
    ]
